apiVersion: v1
kind: Service
metadata:
  name: seldon-service
spec:
  selector:
    app: seldon-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seldon-app
spec:
  selector:
    matchLabels:
      app: seldon-app
  replicas: 5
  template:
    metadata:
      labels:
        app: seldon-app
    spec:
      containers:
      - name: seldon-app
        image: seldon-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000